from django.core.management.base import BaseCommand
from myapp.models import Topic

TOPICS = [
    # basic_math
    "Addition of two numbers",
    "Subtraction of two numbers",
    "Convert minutes to hours and minutes",
    "Multiplication",
    "Division",
    "Perimeter of Polygons",
    "Compare Fractions",
    "Fraction to Decimal",
    "Is Prime",
    "Is Composite",
    "Factors of a number",
    "Fraction Multiplication",
    "Divide Fractions",
    "Volume of a cube",
    "Volume of a cuboid",
    "Absolute difference between two numbers",
    "Exponentiation",
    "Square",
    "Percentage of a number",
    "Greatest Common Divisor of N Numbers ( GCD / HCF )",
    "LCM (Least Common Multiple)",
    "Prime Factors",
    "Common Factors",
    "Combine Like Terms",
    "Area of Triangle",
    "Area of Trapezoid",
    "Surface area of a cube",
    "Surface area of a cuboid",
    "Mean and Median",
    "Basic Algebra",
    "Complementary and Supplementary Angle",
    "Third Angle of Triangle",
    "Fourth Angle of Quadrilateral",
    "Area of Circle",
    "Circumference of Circle",
    "Area of Circle given center and a point on circle",
    "Surface area of a cone",
    "Surface area of a cylinder",
    "Curved surface area of a cylinder",
    "Surface area of a pyramid",
    "Simple Interest",
    "Profit or Loss Percent",
    "Celsius to Fahrenheit",
    "Percentage difference between two numbers",
    "Percentage error",
    "Probability of a certain sum appearing on faces of dice",
    "Square Root",
    "Cube Root",
    "Product of scientific notations",
    "Pythagorean Theorem",
    "Volume of a cylinder",
    "Volume of a cone",
    "Volume of a sphere",
    "Volume of a hemisphere",
    "Surface area of a sphere",
    "Solve a System of Equations in R^2",
    "Linear Equations",
    "Simplify Square Root",
    "Power of Powers",
    "Quotient of Powers with Same Base",
    "Quotient of Powers with Same Power",
    "Comparing Surds",
    "Expanding Factored Binomial",
    "Factoring Quadratic",
    "Quadratic Equation",
    "Intersection of two lines",
    "Equation of Line from Two Points",
    "Equation of line from two points",
    "Compound Interest",
    "Arithmetic Progression Sum",
    "Arithmetic Progression Term",
    "Geometric Progression",
    "Mean, Standard Deviation and Variance",
    "Distance between 2 points",
    "Midpoint of two points",
    "Trigonometric Values",
    "Arc length of Angle",
    "Area of a Sector",
    "Degrees to Radians",
    "Radians to Degrees",
    "Sum of Angles of Polygon",
    "Angle of a Regular Polygon",
    "Valid Triangle",
    "Volume of a pyramid",
    "Volume of the frustum of a cone",
    "Logarithm",
    "Complex Quadratic Equation",
    "Multiplication of 2 complex numbers",
    "Determinant to 2x2 Matrix",
    "Multiply Two Matrices",
    "Multiply Integer to 2x2 Matrix",
    "Invert Matrix",
    "Average Rate of Change over Interval",
    "Factorial",
    "Union, Intersection, Difference of Two Sets",
    "Combinations of Objects",
    "Permutations",
    "Conditional Probability",
    "Binomial distribution",
    "Confidence interval For sample S",
    "Angle between 2 vectors",
    "Angle Sum",
    "Dot product of 2 vectors",
    "Cross product of 2 vectors",
    "Orthogonal Projection",
    "Euclidian norm or L2 norm of a vector",
    "Complex to polar form",
    "Power Rule Differentiation",
    "Power Rule Integration",
    "Definite Integral of Quadratic Equation",
    "Stationary Points",
    "Trigonometric Differentiation",
]


class Command(BaseCommand):
    help = "Seed Topic objects for all mathgenerator functions assigned to a Georgia GSE course"

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for name in TOPICS:
            _, was_created = Topic.objects.get_or_create(topic_name=name)
            if was_created:
                created += 1
            else:
                skipped += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Done: {created} topic(s) created, {skipped} already existed."
            )
        )
